apiVersion: batch/v1
kind: Job
metadata:
  name: pomerium-gen-secrets
spec:
  template:
    metadata:
      name: pomerium-gen-secrets
    spec:
      containers:
        - name: gen-secrets
          args:
            - gen-secrets
            - --secrets=$(POD_NAMESPACE)/bootstrap
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: controller:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        fsGroup: 1000
        runAsUser: 1000
      serviceAccountName: pomerium-gen-secrets
