version: "2"
run:
  build-tags:
    - embed_pomerium
linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 160
    misspell:
      locale: US
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - gocritic
        text: "unnecessaryDefer:"
      - linters:
          - bodyclose
          - errcheck
          - gosec
          - lll
          - maligned
          - mnd
          - scopelint
          - staticcheck
          - unparam
          - unused
        path: _test\.go$|^tests/|^integration/|^samples/|templates\.go$|^internal/stress/
      - linters:
          - lll
        source: "^//go:generate "
      - linters:
          - gosec
        path: internal/identity/google.go
        text: Potential hardcoded credentials
      - linters:
          - staticcheck
        path: internal/identity/google.go
        text: please use NewService instead
      - linters:
          - gosec
        path: internal/identity/oauth/github/github.go
        text: Potential hardcoded credentials
      - linters:
          - golint
          - revive
        text: should have a package comment
      - linters:
          - revive
        text: avoid meaningless package names
      - path: (.+)\.go$
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
      - path: (.+)\.go$
        text: func name will be used as test\.Test.* by other packages, and that stutters; consider calling this
      - path: (.+)\.go$
        text: (possible misuse of unsafe.Pointer|should have signature)
      - path: (.+)\.go$
        text: ineffective break statement. Did you mean to break out of the outer loop
      - path: (.+)\.go$
        text: Use of unsafe calls should be audited
      - path: (.+)\.go$
        text: Subprocess launch(ed with variable|ing should be audited)
      - path: (.+)\.go$
        text: G104
      - path: (.+)\.go$
        text: G117
      - path: (.+)\.go$
        text: (Expect directory permissions to be 0750 or less|Expect file permissions to be 0600 or less)
      - path: (.+)\.go$
        text: Potential file inclusion via variable
      - path: (.+)\.go$
        text: Error return value of `w.Write` is not checked
      - path: (.+)\.go$
        text: Error return value of `io.WriteString` is not checked
      - path: (.+)\.go$
        text: Error return value of `viper.BindEnv` is not checked
      - path: (.+)\.go$
        text: Error return value of `h.Write` is not checked
      - path: (.+)\.go$
        text: ExecuteTemplate` is not checked
      - path: (.+)\.go$
        text: TLS InsecureSkipVerify set true.
      - path: (.+)\.go$
        text: goroutine calls T.Fatalf, which must be called in the same goroutine as the test
      - path: (.+)\.go$
        text: method XXX
      - path: (.+)\.go$
        text: SA1019
      - path: (.+)\.go$
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
      - linters:
          - staticcheck
        path: (.+)\.go$
        text: QF1008
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/pomerium
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
