# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM gcr.io/distroless/base:debug-nonroot@sha256:6691be59b27dde70a2cec7b9794096b8bbf63eec7685062c06e327d1f06a773e
ARG TARGETARCH
COPY bin-$TARGETARCH/manager /manager
USER 65532:65532

ENTRYPOINT ["/manager"]
