apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pomerium-databroker
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pomerium
      app.kubernetes.io/component: databroker
  serviceName: pomerium-databroker
  replicas: 3
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pomerium
        app.kubernetes.io/component: databroker
    spec:
      containers:
        - name: pomerium
      serviceAccountName: pomerium-controller
      terminationGracePeriodSeconds: 10
