apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base.yaml
patches:
  - path: args.yaml
  - path: image.yaml
  - path: no-root.yaml
  - path: ports.yaml
  - path: readonly-root-fs.yaml
  - path: resources.yaml
  - path: volume.yaml
