apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pomerium-databroker
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: pomerium
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsGroup: 65532
            runAsUser: 65532
