apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pomerium-databroker
spec:
  template:
    spec:
      containers:
        - name: pomerium
          volumeMounts:
            - name: storage
              mountPath: /var/pomerium/databroker
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
