// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pomerium/sdk-go (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -package mock_test -destination sdkclient.go -mock_names Client=MockSDKClient github.com/pomerium/sdk-go Client
//

// Package mock_test is a generated GoMock package.
package mock_test

import (
	context "context"
	reflect "reflect"

	connect "connectrpc.com/connect"
	pomerium "github.com/pomerium/sdk-go/proto/pomerium"
	gomock "go.uber.org/mock/gomock"
)

// MockSDKClient is a mock of Client interface.
type MockSDKClient struct {
	ctrl     *gomock.Controller
	recorder *MockSDKClientMockRecorder
	isgomock struct{}
}

// MockSDKClientMockRecorder is the mock recorder for MockSDKClient.
type MockSDKClientMockRecorder struct {
	mock *MockSDKClient
}

// NewMockSDKClient creates a new mock instance.
func NewMockSDKClient(ctrl *gomock.Controller) *MockSDKClient {
	mock := &MockSDKClient{ctrl: ctrl}
	mock.recorder = &MockSDKClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSDKClient) EXPECT() *MockSDKClientMockRecorder {
	return m.recorder
}

// CreateKeyPair mocks base method.
func (m *MockSDKClient) CreateKeyPair(arg0 context.Context, arg1 *connect.Request[pomerium.CreateKeyPairRequest]) (*connect.Response[pomerium.CreateKeyPairResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKeyPair", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[pomerium.CreateKeyPairResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKeyPair indicates an expected call of CreateKeyPair.
func (mr *MockSDKClientMockRecorder) CreateKeyPair(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKeyPair", reflect.TypeOf((*MockSDKClient)(nil).CreateKeyPair), arg0, arg1)
}

// CreatePolicy mocks base method.
func (m *MockSDKClient) CreatePolicy(arg0 context.Context, arg1 *connect.Request[pomerium.CreatePolicyRequest]) (*connect.Response[pomerium.CreatePolicyResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePolicy", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[pomerium.CreatePolicyResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePolicy indicates an expected call of CreatePolicy.
func (mr *MockSDKClientMockRecorder) CreatePolicy(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePolicy", reflect.TypeOf((*MockSDKClient)(nil).CreatePolicy), arg0, arg1)
}

// CreateRoute mocks base method.
func (m *MockSDKClient) CreateRoute(arg0 context.Context, arg1 *connect.Request[pomerium.CreateRouteRequest]) (*connect.Response[pomerium.CreateRouteResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoute", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[pomerium.CreateRouteResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoute indicates an expected call of CreateRoute.
func (mr *MockSDKClientMockRecorder) CreateRoute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoute", reflect.TypeOf((*MockSDKClient)(nil).CreateRoute), arg0, arg1)
}

// CreateServiceAccount mocks base method.
func (m *MockSDKClient) CreateServiceAccount(arg0 context.Context, arg1 *connect.Request[pomerium.CreateServiceAccountRequest]) (*connect.Response[pomerium.CreateServiceAccountResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateServiceAccount", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[pomerium.CreateServiceAccountResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateServiceAccount indicates an expected call of CreateServiceAccount.
func (mr *MockSDKClientMockRecorder) CreateServiceAccount(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServiceAccount", reflect.TypeOf((*MockSDKClient)(nil).CreateServiceAccount), arg0, arg1)
}

// DeleteKeyPair mocks base method.
func (m *MockSDKClient) DeleteKeyPair(arg0 context.Context, arg1 *connect.Request[pomerium.DeleteKeyPairRequest]) (*connect.Response[pomerium.DeleteKeyPairResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKeyPair", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[pomerium.DeleteKeyPairResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteKeyPair indicates an expected call of DeleteKeyPair.
func (mr *MockSDKClientMockRecorder) DeleteKeyPair(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKeyPair", reflect.TypeOf((*MockSDKClient)(nil).DeleteKeyPair), arg0, arg1)
}

// DeletePolicy mocks base method.
func (m *MockSDKClient) DeletePolicy(arg0 context.Context, arg1 *connect.Request[pomerium.DeletePolicyRequest]) (*connect.Response[pomerium.DeletePolicyResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePolicy", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[pomerium.DeletePolicyResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePolicy indicates an expected call of DeletePolicy.
func (mr *MockSDKClientMockRecorder) DeletePolicy(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePolicy", reflect.TypeOf((*MockSDKClient)(nil).DeletePolicy), arg0, arg1)
}

// DeleteRoute mocks base method.
func (m *MockSDKClient) DeleteRoute(arg0 context.Context, arg1 *connect.Request[pomerium.DeleteRouteRequest]) (*connect.Response[pomerium.DeleteRouteResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoute", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[pomerium.DeleteRouteResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRoute indicates an expected call of DeleteRoute.
func (mr *MockSDKClientMockRecorder) DeleteRoute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoute", reflect.TypeOf((*MockSDKClient)(nil).DeleteRoute), arg0, arg1)
}

// DeleteServiceAccount mocks base method.
func (m *MockSDKClient) DeleteServiceAccount(arg0 context.Context, arg1 *connect.Request[pomerium.DeleteServiceAccountRequest]) (*connect.Response[pomerium.DeleteServiceAccountResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServiceAccount", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[pomerium.DeleteServiceAccountResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteServiceAccount indicates an expected call of DeleteServiceAccount.
func (mr *MockSDKClientMockRecorder) DeleteServiceAccount(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServiceAccount", reflect.TypeOf((*MockSDKClient)(nil).DeleteServiceAccount), arg0, arg1)
}

// GetKeyPair mocks base method.
func (m *MockSDKClient) GetKeyPair(arg0 context.Context, arg1 *connect.Request[pomerium.GetKeyPairRequest]) (*connect.Response[pomerium.GetKeyPairResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyPair", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[pomerium.GetKeyPairResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeyPair indicates an expected call of GetKeyPair.
func (mr *MockSDKClientMockRecorder) GetKeyPair(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyPair", reflect.TypeOf((*MockSDKClient)(nil).GetKeyPair), arg0, arg1)
}

// GetPolicy mocks base method.
func (m *MockSDKClient) GetPolicy(arg0 context.Context, arg1 *connect.Request[pomerium.GetPolicyRequest]) (*connect.Response[pomerium.GetPolicyResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPolicy", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[pomerium.GetPolicyResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPolicy indicates an expected call of GetPolicy.
func (mr *MockSDKClientMockRecorder) GetPolicy(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPolicy", reflect.TypeOf((*MockSDKClient)(nil).GetPolicy), arg0, arg1)
}

// GetRoute mocks base method.
func (m *MockSDKClient) GetRoute(arg0 context.Context, arg1 *connect.Request[pomerium.GetRouteRequest]) (*connect.Response[pomerium.GetRouteResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoute", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[pomerium.GetRouteResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoute indicates an expected call of GetRoute.
func (mr *MockSDKClientMockRecorder) GetRoute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoute", reflect.TypeOf((*MockSDKClient)(nil).GetRoute), arg0, arg1)
}

// GetServerInfo mocks base method.
func (m *MockSDKClient) GetServerInfo(arg0 context.Context, arg1 *connect.Request[pomerium.GetServerInfoRequest]) (*connect.Response[pomerium.GetServerInfoResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerInfo", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[pomerium.GetServerInfoResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerInfo indicates an expected call of GetServerInfo.
func (mr *MockSDKClientMockRecorder) GetServerInfo(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerInfo", reflect.TypeOf((*MockSDKClient)(nil).GetServerInfo), arg0, arg1)
}

// GetServiceAccount mocks base method.
func (m *MockSDKClient) GetServiceAccount(arg0 context.Context, arg1 *connect.Request[pomerium.GetServiceAccountRequest]) (*connect.Response[pomerium.GetServiceAccountResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceAccount", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[pomerium.GetServiceAccountResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceAccount indicates an expected call of GetServiceAccount.
func (mr *MockSDKClientMockRecorder) GetServiceAccount(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceAccount", reflect.TypeOf((*MockSDKClient)(nil).GetServiceAccount), arg0, arg1)
}

// GetSettings mocks base method.
func (m *MockSDKClient) GetSettings(arg0 context.Context, arg1 *connect.Request[pomerium.GetSettingsRequest]) (*connect.Response[pomerium.GetSettingsResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSettings", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[pomerium.GetSettingsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSettings indicates an expected call of GetSettings.
func (mr *MockSDKClientMockRecorder) GetSettings(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSettings", reflect.TypeOf((*MockSDKClient)(nil).GetSettings), arg0, arg1)
}

// ListKeyPairs mocks base method.
func (m *MockSDKClient) ListKeyPairs(arg0 context.Context, arg1 *connect.Request[pomerium.ListKeyPairsRequest]) (*connect.Response[pomerium.ListKeyPairsResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKeyPairs", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[pomerium.ListKeyPairsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKeyPairs indicates an expected call of ListKeyPairs.
func (mr *MockSDKClientMockRecorder) ListKeyPairs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKeyPairs", reflect.TypeOf((*MockSDKClient)(nil).ListKeyPairs), arg0, arg1)
}

// ListPolicies mocks base method.
func (m *MockSDKClient) ListPolicies(arg0 context.Context, arg1 *connect.Request[pomerium.ListPoliciesRequest]) (*connect.Response[pomerium.ListPoliciesResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPolicies", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[pomerium.ListPoliciesResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPolicies indicates an expected call of ListPolicies.
func (mr *MockSDKClientMockRecorder) ListPolicies(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPolicies", reflect.TypeOf((*MockSDKClient)(nil).ListPolicies), arg0, arg1)
}

// ListRoutes mocks base method.
func (m *MockSDKClient) ListRoutes(arg0 context.Context, arg1 *connect.Request[pomerium.ListRoutesRequest]) (*connect.Response[pomerium.ListRoutesResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoutes", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[pomerium.ListRoutesResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoutes indicates an expected call of ListRoutes.
func (mr *MockSDKClientMockRecorder) ListRoutes(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoutes", reflect.TypeOf((*MockSDKClient)(nil).ListRoutes), arg0, arg1)
}

// ListServiceAccounts mocks base method.
func (m *MockSDKClient) ListServiceAccounts(arg0 context.Context, arg1 *connect.Request[pomerium.ListServiceAccountsRequest]) (*connect.Response[pomerium.ListServiceAccountsResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServiceAccounts", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[pomerium.ListServiceAccountsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServiceAccounts indicates an expected call of ListServiceAccounts.
func (mr *MockSDKClientMockRecorder) ListServiceAccounts(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServiceAccounts", reflect.TypeOf((*MockSDKClient)(nil).ListServiceAccounts), arg0, arg1)
}

// ListSettings mocks base method.
func (m *MockSDKClient) ListSettings(arg0 context.Context, arg1 *connect.Request[pomerium.ListSettingsRequest]) (*connect.Response[pomerium.ListSettingsResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSettings", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[pomerium.ListSettingsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSettings indicates an expected call of ListSettings.
func (mr *MockSDKClientMockRecorder) ListSettings(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSettings", reflect.TypeOf((*MockSDKClient)(nil).ListSettings), arg0, arg1)
}

// UpdateKeyPair mocks base method.
func (m *MockSDKClient) UpdateKeyPair(arg0 context.Context, arg1 *connect.Request[pomerium.UpdateKeyPairRequest]) (*connect.Response[pomerium.UpdateKeyPairResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKeyPair", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[pomerium.UpdateKeyPairResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateKeyPair indicates an expected call of UpdateKeyPair.
func (mr *MockSDKClientMockRecorder) UpdateKeyPair(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKeyPair", reflect.TypeOf((*MockSDKClient)(nil).UpdateKeyPair), arg0, arg1)
}

// UpdatePolicy mocks base method.
func (m *MockSDKClient) UpdatePolicy(arg0 context.Context, arg1 *connect.Request[pomerium.UpdatePolicyRequest]) (*connect.Response[pomerium.UpdatePolicyResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePolicy", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[pomerium.UpdatePolicyResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePolicy indicates an expected call of UpdatePolicy.
func (mr *MockSDKClientMockRecorder) UpdatePolicy(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePolicy", reflect.TypeOf((*MockSDKClient)(nil).UpdatePolicy), arg0, arg1)
}

// UpdateRoute mocks base method.
func (m *MockSDKClient) UpdateRoute(arg0 context.Context, arg1 *connect.Request[pomerium.UpdateRouteRequest]) (*connect.Response[pomerium.UpdateRouteResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoute", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[pomerium.UpdateRouteResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRoute indicates an expected call of UpdateRoute.
func (mr *MockSDKClientMockRecorder) UpdateRoute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoute", reflect.TypeOf((*MockSDKClient)(nil).UpdateRoute), arg0, arg1)
}

// UpdateServiceAccount mocks base method.
func (m *MockSDKClient) UpdateServiceAccount(arg0 context.Context, arg1 *connect.Request[pomerium.UpdateServiceAccountRequest]) (*connect.Response[pomerium.UpdateServiceAccountResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServiceAccount", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[pomerium.UpdateServiceAccountResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateServiceAccount indicates an expected call of UpdateServiceAccount.
func (mr *MockSDKClientMockRecorder) UpdateServiceAccount(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServiceAccount", reflect.TypeOf((*MockSDKClient)(nil).UpdateServiceAccount), arg0, arg1)
}

// UpdateSettings mocks base method.
func (m *MockSDKClient) UpdateSettings(arg0 context.Context, arg1 *connect.Request[pomerium.UpdateSettingsRequest]) (*connect.Response[pomerium.UpdateSettingsResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSettings", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[pomerium.UpdateSettingsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSettings indicates an expected call of UpdateSettings.
func (mr *MockSDKClientMockRecorder) UpdateSettings(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSettings", reflect.TypeOf((*MockSDKClient)(nil).UpdateSettings), arg0, arg1)
}
