namespace: pomerium
resources:
  - ../default
  - ./statefulset
  - ./service
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: '--services=authenticate,authorize,proxy'
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: '--databroker-service-urls=https://pomerium-databroker-0.pomerium-databroker:5443'
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: '--databroker-service-urls=https://pomerium-databroker-1.pomerium-databroker:5443'
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: '--databroker-service-urls=https://pomerium-databroker-2.pomerium-databroker:5443'
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: '--databroker-auto-tls=*.pomerium-databroker'
    target:
      group: apps
      version: v1
      kind: Deployment
      name: pomerium
