apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pomerium
  namespace: pomerium
spec:
  endpoints:
    - path: /metrics
      port: metrics
      scheme: http
  selector:
    matchLabels:
      control-plane: controller-manager
