apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomerium
spec:
  selector: {}
  replicas: 1
  template:
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: pomerium
          command:
            - /manager
          args:
            - all-in-one
            - --global-settings=$(POMERIUM_NAMESPACE)/settings
            - --update-status-from-service=$(POMERIUM_NAMESPACE)/pomerium-proxy
            - --metrics-bind-address=$(POD_IP):9090
          image: controller:latest
          ports:
            - containerPort: 443
              name: https
              protocol: TCP
            - name: http
              containerPort: 80
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          env:
            - name: POMERIUM_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            limits:
              cpu: 5000m
              memory: 1Gi
            requests:
              cpu: 1000m
              memory: 200Mi
      serviceAccountName: pomerium-controller
      terminationGracePeriodSeconds: 10
