#
# Deploys all-in-one controller + core pomerium
#
resources:
  - namespace.yaml
  - deployment.yaml
  - service_proxy.yaml
  - service_metrics.yaml
  - service_account.yaml
  - role.yaml
  - role_binding.yaml
  - ingressclass.yaml
