apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomerium
  labels:
    app.kubernetes.io/name: pomerium
    app.kubernetes.io/component: proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pomerium
        app.kubernetes.io/component: proxy
    spec:
      containers:
        - name: pomerium
      serviceAccountName: pomerium-controller
      terminationGracePeriodSeconds: 10
