apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomerium
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: pomerium
      serviceAccountName: pomerium-controller
      terminationGracePeriodSeconds: 10
