apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomerium
spec:
  template:
    spec:
      containers:
        - name: pomerium
          startupProbe:
            httpGet:
              path: /startupz
              port : 28080
            failureThreshold: 40
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /healthz
              port: 28080
            initialDelaySeconds: 15
            periodSeconds: 60
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 28080
            initialDelaySeconds: 15
            periodSeconds: 60
            failureThreshold: 5
