apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomerium
spec:
  template:
    spec:
      containers:
        - name: pomerium
          ports:
            - containerPort: 443
              name: https
              protocol: TCP
            - containerPort: 443
              name: quic
              protocol: UDP
            - name: http
              containerPort: 80
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
