//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Authenticate) DeepCopyInto(out *Authenticate) {
	*out = *in
	if in.CallbackPath != nil {
		in, out := &in.CallbackPath, &out.CallbackPath
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Authenticate.
func (in *Authenticate) DeepCopy() *Authenticate {
	if in == nil {
		return nil
	}
	out := new(Authenticate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CircuitBreakerThresholds) DeepCopyInto(out *CircuitBreakerThresholds) {
	*out = *in
	if in.MaxConnections != nil {
		in, out := &in.MaxConnections, &out.MaxConnections
		*out = new(uint32)
		**out = **in
	}
	if in.MaxPendingRequests != nil {
		in, out := &in.MaxPendingRequests, &out.MaxPendingRequests
		*out = new(uint32)
		**out = **in
	}
	if in.MaxRequests != nil {
		in, out := &in.MaxRequests, &out.MaxRequests
		*out = new(uint32)
		**out = **in
	}
	if in.MaxRetries != nil {
		in, out := &in.MaxRetries, &out.MaxRetries
		*out = new(uint32)
		**out = **in
	}
	if in.MaxConnectionPools != nil {
		in, out := &in.MaxConnectionPools, &out.MaxConnectionPools
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CircuitBreakerThresholds.
func (in *CircuitBreakerThresholds) DeepCopy() *CircuitBreakerThresholds {
	if in == nil {
		return nil
	}
	out := new(CircuitBreakerThresholds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cookie) DeepCopyInto(out *Cookie) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Domain != nil {
		in, out := &in.Domain, &out.Domain
		*out = new(string)
		**out = **in
	}
	if in.HTTPOnly != nil {
		in, out := &in.HTTPOnly, &out.HTTPOnly
		*out = new(bool)
		**out = **in
	}
	if in.Expire != nil {
		in, out := &in.Expire, &out.Expire
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.SameSite != nil {
		in, out := &in.SameSite, &out.SameSite
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cookie.
func (in *Cookie) DeepCopy() *Cookie {
	if in == nil {
		return nil
	}
	out := new(Cookie)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNS) DeepCopyInto(out *DNS) {
	*out = *in
	if in.LookupFamily != nil {
		in, out := &in.LookupFamily, &out.LookupFamily
		*out = new(string)
		**out = **in
	}
	if in.FailureRefreshRate != nil {
		in, out := &in.FailureRefreshRate, &out.FailureRefreshRate
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.QueryTimeout != nil {
		in, out := &in.QueryTimeout, &out.QueryTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.QueryTries != nil {
		in, out := &in.QueryTries, &out.QueryTries
		*out = new(uint32)
		**out = **in
	}
	if in.RefreshRate != nil {
		in, out := &in.RefreshRate, &out.RefreshRate
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.UDPMaxQueries != nil {
		in, out := &in.UDPMaxQueries, &out.UDPMaxQueries
		*out = new(uint32)
		**out = **in
	}
	if in.UseTCP != nil {
		in, out := &in.UseTCP, &out.UseTCP
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNS.
func (in *DNS) DeepCopy() *DNS {
	if in == nil {
		return nil
	}
	out := new(DNS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataBroker) DeepCopyInto(out *DataBroker) {
	*out = *in
	if in.ClusterLeaderID != nil {
		in, out := &in.ClusterLeaderID, &out.ClusterLeaderID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataBroker.
func (in *DataBroker) DeepCopy() *DataBroker {
	if in == nil {
		return nil
	}
	out := new(DataBroker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownstreamMTLS) DeepCopyInto(out *DownstreamMTLS) {
	*out = *in
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.CRL != nil {
		in, out := &in.CRL, &out.CRL
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.Enforcement != nil {
		in, out := &in.Enforcement, &out.Enforcement
		*out = new(string)
		**out = **in
	}
	if in.MatchSubjectAltNames != nil {
		in, out := &in.MatchSubjectAltNames, &out.MatchSubjectAltNames
		*out = new(MatchSubjectAltNames)
		**out = **in
	}
	if in.MaxVerifyDepth != nil {
		in, out := &in.MaxVerifyDepth, &out.MaxVerifyDepth
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownstreamMTLS.
func (in *DownstreamMTLS) DeepCopy() *DownstreamMTLS {
	if in == nil {
		return nil
	}
	out := new(DownstreamMTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityProvider) DeepCopyInto(out *IdentityProvider) {
	*out = *in
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.ServiceAccountFromSecret != nil {
		in, out := &in.ServiceAccountFromSecret, &out.ServiceAccountFromSecret
		*out = new(string)
		**out = **in
	}
	if in.RequestParams != nil {
		in, out := &in.RequestParams, &out.RequestParams
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RequestParamsSecret != nil {
		in, out := &in.RequestParamsSecret, &out.RequestParamsSecret
		*out = new(string)
		**out = **in
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RefreshDirectory != nil {
		in, out := &in.RefreshDirectory, &out.RefreshDirectory
		*out = new(RefreshDirectorySettings)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityProvider.
func (in *IdentityProvider) DeepCopy() *IdentityProvider {
	if in == nil {
		return nil
	}
	out := new(IdentityProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchSubjectAltNames) DeepCopyInto(out *MatchSubjectAltNames) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchSubjectAltNames.
func (in *MatchSubjectAltNames) DeepCopy() *MatchSubjectAltNames {
	if in == nil {
		return nil
	}
	out := new(MatchSubjectAltNames)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OTEL) DeepCopyInto(out *OTEL) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Sampling != nil {
		in, out := &in.Sampling, &out.Sampling
		*out = new(string)
		**out = **in
	}
	if in.ResourceAttributes != nil {
		in, out := &in.ResourceAttributes, &out.ResourceAttributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.BSPScheduleDelay != nil {
		in, out := &in.BSPScheduleDelay, &out.BSPScheduleDelay
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.BSPMaxExportBatchSize != nil {
		in, out := &in.BSPMaxExportBatchSize, &out.BSPMaxExportBatchSize
		*out = new(int32)
		**out = **in
	}
	if in.LogLevel != nil {
		in, out := &in.LogLevel, &out.LogLevel
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OTEL.
func (in *OTEL) DeepCopy() *OTEL {
	if in == nil {
		return nil
	}
	out := new(OTEL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pomerium) DeepCopyInto(out *Pomerium) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pomerium.
func (in *Pomerium) DeepCopy() *Pomerium {
	if in == nil {
		return nil
	}
	out := new(Pomerium)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Pomerium) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PomeriumList) DeepCopyInto(out *PomeriumList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Pomerium, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PomeriumList.
func (in *PomeriumList) DeepCopy() *PomeriumList {
	if in == nil {
		return nil
	}
	out := new(PomeriumList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PomeriumList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PomeriumSpec) DeepCopyInto(out *PomeriumSpec) {
	*out = *in
	if in.AccessLogFields != nil {
		in, out := &in.AccessLogFields, &out.AccessLogFields
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.Authenticate != nil {
		in, out := &in.Authenticate, &out.Authenticate
		*out = new(Authenticate)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthorizeLogFields != nil {
		in, out := &in.AuthorizeLogFields, &out.AuthorizeLogFields
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.Certificates != nil {
		in, out := &in.Certificates, &out.Certificates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CASecrets != nil {
		in, out := &in.CASecrets, &out.CASecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Cookie != nil {
		in, out := &in.Cookie, &out.Cookie
		*out = new(Cookie)
		(*in).DeepCopyInto(*out)
	}
	if in.IdentityProvider != nil {
		in, out := &in.IdentityProvider, &out.IdentityProvider
		*out = new(IdentityProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.JWTClaimHeaders != nil {
		in, out := &in.JWTClaimHeaders, &out.JWTClaimHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PassIdentityHeaders != nil {
		in, out := &in.PassIdentityHeaders, &out.PassIdentityHeaders
		*out = new(bool)
		**out = **in
	}
	if in.ProgrammaticRedirectDomains != nil {
		in, out := &in.ProgrammaticRedirectDomains, &out.ProgrammaticRedirectDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RuntimeFlags != nil {
		in, out := &in.RuntimeFlags, &out.RuntimeFlags
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SetResponseHeaders != nil {
		in, out := &in.SetResponseHeaders, &out.SetResponseHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(Storage)
		(*in).DeepCopyInto(*out)
	}
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(Timeouts)
		(*in).DeepCopyInto(*out)
	}
	if in.UseProxyProtocol != nil {
		in, out := &in.UseProxyProtocol, &out.UseProxyProtocol
		*out = new(bool)
		**out = **in
	}
	if in.CodecType != nil {
		in, out := &in.CodecType, &out.CodecType
		*out = new(string)
		**out = **in
	}
	if in.BearerTokenFormat != nil {
		in, out := &in.BearerTokenFormat, &out.BearerTokenFormat
		*out = new(string)
		**out = **in
	}
	if in.IDPAccessTokenAllowedAudiences != nil {
		in, out := &in.IDPAccessTokenAllowedAudiences, &out.IDPAccessTokenAllowedAudiences
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.OTEL != nil {
		in, out := &in.OTEL, &out.OTEL
		*out = new(OTEL)
		(*in).DeepCopyInto(*out)
	}
	if in.DownstreamMTLS != nil {
		in, out := &in.DownstreamMTLS, &out.DownstreamMTLS
		*out = new(DownstreamMTLS)
		(*in).DeepCopyInto(*out)
	}
	if in.CircuitBreakerThresholds != nil {
		in, out := &in.CircuitBreakerThresholds, &out.CircuitBreakerThresholds
		*out = new(CircuitBreakerThresholds)
		(*in).DeepCopyInto(*out)
	}
	if in.DataBroker != nil {
		in, out := &in.DataBroker, &out.DataBroker
		*out = new(DataBroker)
		(*in).DeepCopyInto(*out)
	}
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = new(DNS)
		(*in).DeepCopyInto(*out)
	}
	if in.SSH != nil {
		in, out := &in.SSH, &out.SSH
		*out = new(SSH)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PomeriumSpec.
func (in *PomeriumSpec) DeepCopy() *PomeriumSpec {
	if in == nil {
		return nil
	}
	out := new(PomeriumSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PomeriumStatus) DeepCopyInto(out *PomeriumStatus) {
	*out = *in
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make(map[string]ResourceStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.SettingsStatus != nil {
		in, out := &in.SettingsStatus, &out.SettingsStatus
		*out = new(ResourceStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PomeriumStatus.
func (in *PomeriumStatus) DeepCopy() *PomeriumStatus {
	if in == nil {
		return nil
	}
	out := new(PomeriumStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresStorage) DeepCopyInto(out *PostgresStorage) {
	*out = *in
	if in.TLSSecret != nil {
		in, out := &in.TLSSecret, &out.TLSSecret
		*out = new(string)
		**out = **in
	}
	if in.CASecret != nil {
		in, out := &in.CASecret, &out.CASecret
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresStorage.
func (in *PostgresStorage) DeepCopy() *PostgresStorage {
	if in == nil {
		return nil
	}
	out := new(PostgresStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RefreshDirectorySettings) DeepCopyInto(out *RefreshDirectorySettings) {
	*out = *in
	out.Interval = in.Interval
	out.Timeout = in.Timeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RefreshDirectorySettings.
func (in *RefreshDirectorySettings) DeepCopy() *RefreshDirectorySettings {
	if in == nil {
		return nil
	}
	out := new(RefreshDirectorySettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceStatus) DeepCopyInto(out *ResourceStatus) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
	if in.Error != nil {
		in, out := &in.Error, &out.Error
		*out = new(string)
		**out = **in
	}
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceStatus.
func (in *ResourceStatus) DeepCopy() *ResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSH) DeepCopyInto(out *SSH) {
	*out = *in
	if in.HostKeySecrets != nil {
		in, out := &in.HostKeySecrets, &out.HostKeySecrets
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.UserCAKeySecret != nil {
		in, out := &in.UserCAKeySecret, &out.UserCAKeySecret
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSH.
func (in *SSH) DeepCopy() *SSH {
	if in == nil {
		return nil
	}
	out := new(SSH)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Storage) DeepCopyInto(out *Storage) {
	*out = *in
	if in.Postgres != nil {
		in, out := &in.Postgres, &out.Postgres
		*out = new(PostgresStorage)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Storage.
func (in *Storage) DeepCopy() *Storage {
	if in == nil {
		return nil
	}
	out := new(Storage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Timeouts) DeepCopyInto(out *Timeouts) {
	*out = *in
	if in.Read != nil {
		in, out := &in.Read, &out.Read
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Write != nil {
		in, out := &in.Write, &out.Write
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Idle != nil {
		in, out := &in.Idle, &out.Idle
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Timeouts.
func (in *Timeouts) DeepCopy() *Timeouts {
	if in == nil {
		return nil
	}
	out := new(Timeouts)
	in.DeepCopyInto(out)
	return out
}
