apiVersion: v1
kind: Service
metadata:
  name: pomerium-proxy
  labels:
    app.kubernetes.io/name: pomerium
    app.kubernetes.io/component: proxy
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: pomerium
    app.kubernetes.io/component: proxy
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
    - name: quic
      port: 443
      targetPort: quic
      protocol: UDP
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
