apiVersion: v1
kind: Service
metadata:
  name: pomerium-proxy
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
    - port: 443
      targetPort: quic
      protocol: UDP
      name: quic
    - name: http
      targetPort: http
      protocol: TCP
      port: 80
