apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pomerium-stress-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pomerium-stress-test
subjects:
  - kind: ServiceAccount
    name: pomerium-stress-test
