---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pomerium-stress-test
rules:
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - create
      - update
      - delete
