name: Docs
on:
  push:
    branches:
      - main

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
        with:
          go-version-file: .tool-versions

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version-file: .tool-versions

      - name: generate docs
        run: make docs

      - name: Create pull request in the documentations repo
        env:
          API_TOKEN_GITHUB: ${{ secrets.APPARITOR_GITHUB_TOKEN }}
          USER_EMAIL: ${{ github.event.pusher.email }}
          USER_NAME: ${{ github.event.pusher.name }}
        run: scripts/open-docs-pull-request.sh
