name: Release
permissions:
  contents: read

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: Check image reference
        # check that docker image reference is the same as the release tag
        run: ./scripts/check-image-tag.sh ${{ github.event.release.tag_name }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf
        with:
          images: |
            pomerium/ingress-controller
            docker.cloudsmith.io/pomerium/ingress-controller/ingress-controller
          tags: |
            type=semver,pattern={{raw}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd

      - name: Login to DockerHub
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to cloudsmith registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2
        with:
          registry: docker.cloudsmith.io
          username: ${{ secrets.CLOUDSMITH_USER }}
          password: ${{ secrets.CLOUDSMITH_API_KEY }}

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version-file: .tool-versions

      - name: Build
        run: make build-ci

      - name: Docker Publish - Main
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294
        with:
          context: .
          file: ./Dockerfile.ci
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
